# Dependabot configuration for Mini MCP
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go modules dependency updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "damirmukimov"
    assignees:
      - "damirmukimov"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automated"
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      go-major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    ignore:
      # Ignore major version updates for specific packages
      - dependency-name: "github.com/gin-gonic/gin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/spf13/cobra"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "damirmukimov"
    assignees:
      - "damirmukimov"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
      - "automated"
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker dependency updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "damirmukimov"
    assignees:
      - "damirmukimov"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    groups:
      docker-updates:
        patterns:
          - "*"
