name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:

jobs:
  stale:
    name: Mark stale issues and pull requests
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Mark stale issues and pull requests
      uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. If you believe this issue is still relevant,
          please add a comment or remove the stale label.
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. If you believe this PR is still relevant,
          please add a comment or remove the stale label.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        close-issue-message: |
          This issue has been automatically closed due to inactivity.
          If you believe this issue is still relevant, please open a new issue.
        close-pr-message: |
          This pull request has been automatically closed due to inactivity.
          If you believe this PR is still relevant, please open a new pull request.
        days-before-stale: 30
        days-before-close: 7
        operations-per-run: 100
        remove-stale-when-updated: true
        debug-only: false
